const contributorsByYear = [
  {
    year: 2025,
    members: [
      {
        login: "becky-n",
        name: "Becky Ngan",
        avatar_url: "https://avatars.githubusercontent.com/u/51529481?v=4",
        profile: "https://github.com/becky-n",
        roles: ["project manager"],
      },
      {
        login: "harbassan",
        name: "Hartej Bassan",
        avatar_url: "https://avatars.githubusercontent.com/u/84175605?v=4",
        profile: "https://github.com/harbassan",
        roles: ["tech lead"],
      },
      {
        login: "mshi672",
        name: "Mike Shi",
        avatar_url: "https://avatars.githubusercontent.com/u/162376891?v=4",
        profile: "https://github.com/mshi672",
        roles: ["design lead", "developer"],
      },
      {
        login: "hazikchaudhry",
        name: "Hazik Chaudhry",
        avatar_url: "https://avatars.githubusercontent.com/u/99319319?v=4",
        profile: "https://github.com/hazikchaudhry",
        roles: ["developer"],
      },
      {
        login: "IceBear-2000",
        name: "Moksh Manglani",
        avatar_url: "https://avatars.githubusercontent.com/u/160542881?v=4",
        profile: "https://github.com/IceBear-2000",
        roles: ["developer"],
      },
      {
        login: "kelvinchen8",
        name: "Kelvin Chen",
        avatar_url: "https://avatars.githubusercontent.com/u/161402193?v=4",
        profile: "https://github.com/kelvinchen8",
        roles: ["developer"],
      },
      {
        login: "oorjagandhi",
        name: "Oorja Gandhi",
        avatar_url: "https://avatars.githubusercontent.com/u/72714597?v=4",
        profile: "https://github.com/oorjagandhi",
        roles: ["developer"],
      },
      {
        login: "Richman-Tan",
        name: "Richman Tan",
        avatar_url: "https://avatars.githubusercontent.com/u/160602954?v=4",
        profile: "https://github.com/Richman-Tan",
        roles: ["developer"],
      },
      {
        login: "RLee64",
        name: "Rayen Lee",
        avatar_url: "https://avatars.githubusercontent.com/u/159082701?v=4",
        profile: "https://github.com/RLee64",
        roles: ["developer"],
      },
      {
        login: "R4H3N",
        name: "Rohan Dhingra",
        avatar_url: "https://avatars.githubusercontent.com/u/126861359?v=4",
        profile: "https://github.com/R4H3N",
        roles: ["developer"],
      },
      {
        login: "Brad123ghost",
        name: "Bradley Chung",
        avatar_url: "https://avatars.githubusercontent.com/u/32890981?v=4",
        profile: "https://github.com/Brad123ghost",
        roles: ["developer"],
      },
      {
        login: "chrisv09",
        name: "Chris Valenzuela",
        avatar_url: "https://avatars.githubusercontent.com/u/55444457?v=4",
        profile: "https://github.com/chrisv09",
        roles: ["user testing facilitator"],
      },
      {
        login: "Oculux314",
        name: "Nate Williamson",
        avatar_url: "https://avatars.githubusercontent.com/u/121474948?v=4",
        profile: "https://github.com/Oculux314",
        roles: ["infrastructure"],
      },
    ],
  },
  {
    year: 2024,
    members: [
      {
        login: "JordanBlenn",
        name: "Jordan Blennerhassett",
        avatar_url: "https://avatars.githubusercontent.com/u/127293604?v=4",
        profile: "https://github.com/JordanBlenn",
        roles: ["project manager"],
      },
      {
        login: "wjin-lee",
        name: "Woo Jin Lee",
        avatar_url: "https://avatars.githubusercontent.com/u/100455176?v=4",
        profile: "https://github.com/wjin-lee",
        roles: ["tech lead"],
      },
      {
        login: "harbassan",
        name: "Hartej Bassan",
        avatar_url: "https://avatars.githubusercontent.com/u/84175605?v=4",
        profile: "https://github.com/harbassan",
        roles: ["developer"],
      },
      {
        login: "itsatulbox",
        name: "Atul Kodla",
        avatar_url: "https://avatars.githubusercontent.com/u/161205868?v=4",
        profile: "https://github.com/itsatulbox",
        roles: ["developer"],
      },
      {
        login: "laibatool792",
        name: "Laiba Batool",
        avatar_url: "https://avatars.githubusercontent.com/u/133545972?v=4",
        profile: "https://github.com/laibatool792",
        roles: ["developer"],
      },
      {
        login: "sbeen56",
        name: "Subeen Ban",
        avatar_url: "https://avatars.githubusercontent.com/u/161543207?v=4",
        profile: "https://github.com/sbeen56",
        roles: ["developer"],
      },
      {
        login: "xche529",
        name: "Tommy Chen",
        avatar_url: "https://avatars.githubusercontent.com/u/126313171?v=4",
        profile: "https://github.com/xche529",
        roles: ["developer"],
      },
      {
        login: "codecreator127",
        name: "John Lin",
        avatar_url: "https://avatars.githubusercontent.com/u/120153300?v=4",
        profile: "https://github.com/codecreator127",
        roles: ["developer"],
      },
      {
        login: "jacobmathew105",
        name: "Jacob Mathew",
        avatar_url: "https://avatars.githubusercontent.com/u/136278107?v=4",
        profile: "https://github.com/jacobmathew105",
        roles: ["developer"],
      },
      {
        login: "koutaroyumiba",
        name: "Koutaro Yumiba",
        avatar_url: "https://avatars.githubusercontent.com/u/136278107?v=4",
        profile: "https://github.com/koutaroyumiba",
        roles: ["developer"],
      },
      {
        login: "nroh555",
        name: "Naren Rohan",
        avatar_url: "https://avatars.githubusercontent.com/u/100507962?v=4",
        profile: "https://github.com/nroh555",
        roles: ["infrastructure"],
      },
    ],
  },
  {
    year: 2023,
    members: [
      {
        login: "Ryuna001",
        name: "Ryan In",
        avatar_url: "https://avatars.githubusercontent.com/u/127585171?v=4",
        profile: "https://github.com/Ryuna001",
        roles: ["project manager"],
      },
      {
        login: "djos192",
        name: "Dhruv Joshi",
        avatar_url: "https://avatars.githubusercontent.com/u/100509811?v=4",
        profile: "https://github.com/djos192",
        roles: ["tech lead"],
      },
      {
        login: "John-Moore-UOA",
        name: "John Moore",
        avatar_url: "https://avatars.githubusercontent.com/u/126381092?v=4",
        profile: "https://john-moore-uoa.github.io/Profile-Website/",
        roles: ["developer"],
      },
      {
        login: "j-enn-y",
        name: "Jenny Lu",
        avatar_url: "https://avatars.githubusercontent.com/u/127184310?v=4",
        profile: "https://github.com/j-enn-y",
        roles: ["developer"],
      },
      {
        login: "GodYazza",
        name: "Yang Qian",
        avatar_url: "https://avatars.githubusercontent.com/u/30404287?v=4",
        profile: "https://github.com/GodYazza",
        roles: ["developer"],
      },
      {
        login: "quirked-up",
        name: "Lilith Wiegand",
        avatar_url: "https://avatars.githubusercontent.com/u/115190871?v=4",
        profile: "https://github.com/quirked-up",
        roles: ["developer"],
      },
      {
        login: "arnard76",
        name: "Arnav Shekaran",
        avatar_url: "https://avatars.githubusercontent.com/u/78939786?v=4",
        profile: "https://grow-run-archive.vercel.app/welcome",
        roles: ["developer"],
      },
      {
        login: "Ray-F",
        name: "Raymond Feng",
        avatar_url: "https://avatars.githubusercontent.com/u/19633284?v=4",
        profile: "https://github.com/Ray-F",
        roles: ["infrastructure"],
      },
    ],
  },
  {
    year: 2022,
    members: [
      {
        login: "nicholas-kondal",
        name: "Nicholas Kondal",
        avatar_url: "https://avatars.githubusercontent.com/u/49134354?v=4",
        profile: "https://www.nicholaskondal.com/",
        roles: ["project manager"],
      },
      {
        login: "Harshal-D",
        name: "Harshal Damania",
        avatar_url: "https://avatars.githubusercontent.com/u/41532279?v=4",
        profile: "https://github.com/Harshal-D",
        roles: ["assistant project manager"],
      },
      {
        login: "DamonGreenhalgh",
        name: "Damon Greenhalgh",
        avatar_url: "https://avatars.githubusercontent.com/u/59471444?v=4",
        profile: "https://www.damongreenhalgh.com/",
        roles: ["developer"],
      },
      {
        login: "aadenmann",
        name: "Aden Ing",
        avatar_url: "https://avatars.githubusercontent.com/u/101456326?v=4",
        profile: "https://github.com/aadenmann",
        roles: ["developer"],
      },
      {
        login: "KW781",
        name: "Aarnob Guha",
        avatar_url: "https://avatars.githubusercontent.com/u/59013794?v=4",
        profile: "https://github.com/KW781",
        roles: ["developer"],
      },
      {
        login: "lia-arroyo",
        name: "Lia Arroyo",
        avatar_url: "https://avatars.githubusercontent.com/u/94775011?v=4",
        profile: "https://github.com/lia-arroyo",
        roles: ["developer"],
      },
      {
        login: "retinfai",
        name: "Afereti Pama",
        avatar_url: "https://avatars.githubusercontent.com/u/79831813?v=4",
        profile: "https://github.com/retinfai",
        roles: ["developer"],
      },
      {
        login: "jfen445",
        name: "Josh Feng",
        avatar_url: "https://avatars.githubusercontent.com/u/79815130?v=4",
        profile: "https://github.com/jfen445",
        roles: ["developer"],
      },
      {
        login: "mlai962",
        name: "Matthew Lai",
        avatar_url: "https://avatars.githubusercontent.com/u/79812370?v=4",
        profile: "https://github.com/mlai962",
        roles: ["developer"],
      },
      {
        login: "Ray-F",
        name: "Raymond Feng",
        avatar_url: "https://avatars.githubusercontent.com/u/19633284?v=4",
        profile: "https://github.com/Ray-F",
        roles: ["infrastructure"],
      },
    ],
  },
  {
    year: 2021,
    members: [
      {
        login: "lucas2005gao",
        name: "Lucas Gao",
        avatar_url: "https://avatars.githubusercontent.com/u/48196609?v=4",
        profile: "https://github.com/lucas2005gao",
        roles: ["developer"],
      },
      {
        login: "flexzy",
        name: "Felix Yang",
        avatar_url: "https://avatars.githubusercontent.com/u/49087744?v=4",
        profile: "https://github.com/flexzy",
        roles: ["developer"],
      },
      {
        login: "David-Xia0",
        name: "David Xiao",
        avatar_url: "https://avatars.githubusercontent.com/u/50573329?v=4",
        profile: "https://github.com/David-Xia0",
        roles: ["developer"],
      },
      {
        login: "zyan225",
        name: "Emily Yang",
        avatar_url: "https://avatars.githubusercontent.com/u/52368549?v=4",
        profile: "https://github.com/zyan225",
        roles: ["developer"],
      },
      {
        login: "dongmeilim",
        name: "Dong Mei Lim",
        avatar_url: "https://avatars.githubusercontent.com/u/52555301?v=4",
        profile: "https://github.com/dongmeilim",
        roles: ["developer"],
      },
      {
        login: "annithinggoes",
        name: "Annie Chau",
        avatar_url: "https://avatars.githubusercontent.com/u/52563454?v=4",
        profile: "https://github.com/annithinggoes",
        roles: ["developer"],
      },
      {
        login: "afei088",
        name: "Andrew Fei",
        avatar_url: "https://avatars.githubusercontent.com/u/60560589?v=4",
        profile: "https://github.com/afei088",
        roles: ["developer"],
      },
    ],
  },
];

export default contributorsByYear;
