app = 'wdcc-vps-staging'
primary_region = 'syd'
swap_size_mb = 512

[build]
  # dockerfile contains build time non-sensitive env vars
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256