name: Deploy DEV

on: [workflow_dispatch]

jobs:
  DeployFrontend:
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Create env file
        run: echo ${{ secrets.FRONTEND_ENVFILE }} | base64 --decode > .env

      - run: yarn install --frozen-lockfile
      - run: CI=false yarn build

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          # Credentials stored inside WDCC organisation secrets
          credentials_json: "${{ secrets.VPS_GCP_DEPLOYMENT_SA_CREDENTIALS }}"

      - id: "upload"
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "frontend/build"
          # Cloud Storage Bucket to add contents into
          destination: "vps-dev.wdcc.co.nz"
          parent: false
          project_id: wdcc-vps-dev

  DeployBackend:
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Create env file
        run: echo ${{ secrets.BACKEND_ENVFILE }} | base64 --decode > gae_env.yaml

      - run: yarn install --frozen-lockfile

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          # Credentials stored inside WDCC organisation secrets
          credentials_json: "${{ secrets.VPS_GCP_DEPLOYMENT_SA_CREDENTIALS }}"

      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v2"
        with:
          flags: --no-cache
          project_id: wdcc-vps-dev
          working_directory: ./backend
