name: Prettier

on:
  workflow_dispatch
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"

jobs:
  run-prettier-frontend:
    name: Run prettier frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Installs dev dependencies
      - name: Install dev dependencies
        run: yarn install

      # Runs prettier
      - name: Run code style check
        run: yarn run prettier

  run-prettier-backend:
    name: Run prettier backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Installs dev dependencies
      - name: Install dev dependencies
        run: yarn install

      # Runs prettier
      - name: Run code style check
        run: yarn run prettier
